### ISSUE TITLE
iOS project and Android project are not building

### ISSUE THREAD

**Issue by Fox9MonoGame** [dmanning23/RevMobBuddySample#1]
For the iOS project, I get this message:
![ioserror](https://user-images.githubusercontent.com/7604007/46571369-33f6c600-c974-11e8-8a55-4fa62a81c56a.png)

And for the Anfroid project I get some spriteFont error messages, for example this one:
/Users/.../Desktop/RevMobBuddySample-master-2/RevMobBuddyExample.SharedProject/Content/Fonts/ArialBlack10.spritefont: Error: Index was out of range. Must be non-negative and less than the size of the collection. (RevMobBuddyExample.Android)

And this error message in the following line in Activity1.cs:
`    <Exec Condition=" '%(ContentReferences.FullPath)' != '' " Command="$(MonoGameContentBuilderCmd) /@:&quot;%(ContentReferences.FullPath)&quot; $(Header)"`
/Library/Frameworks/Mono.framework/External/xbuild/MonoGame/v3.0/MonoGame.Content.Builder.targets(5,5): Error MSB3073: The command "/Library/Frameworks/Mono.framework/Versions/Current/bin/mono "/Library/Frameworks/Mono.framework/External/xbuild/MonoGame/v3.0/Tools/MGCB.exe" /@:"/Users/.../Desktop/RevMobBuddySample-master-2/RevMobBuddyExample.SharedProject/Content/Content.mgcb" /platform:Android /outputDir:"/Users/.../Desktop/RevMobBuddySample-master-2/RevMobBuddyExample.Android/Content/bin/Android" /intermediateDir:"/Users/.../Desktop/RevMobBuddySample-master-2/RevMobBuddyExample.Android/Content/obj/Android" /quiet" exited with code 8. (MSB3073) (RevMobBuddyExample.Android)

**Comment by dmanning23** [comment]
Ok, cleaned up the Xamarin Component error message. 
Not sure what the spritefont error is though. I've used those spritefonts in dozens of projects and never had problems, but I am still running MonoGame 3.6. Do you have the Arial Black font installed on your computer? What version of MonoGame do you have installed?

**Comment by Fox9MonoGame** [comment]
MonoGame Pipeline Tool 3.7.0.1708 and MonoGame 3.7.0.1(in Visual Studio Community 2017 for Mac) are installed. Arial Black is installed.
I did a new installation of MonoGame and the spritefonts are working now.

**Comment by dmanning23** [comment]
I'm in the middle of a big project and can't update to 3.7 right now. You can remove that spritefont and add one of yours that is working, and change the Game.InitStyles() method to swap it out.

**Comment by dmanning23** [comment]
Updated all this to MonoGame 3.71 awhile ago.
Closing this ticket.
